//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIT.TFS.SyncService.Adapter.TFS2012.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIT.TFS.SyncService.Adapter.TFS2012.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF210005: Your display name from Active Directory cannot be used to subscribe for work item events. It contains both ‘ and “ characters. Remove these characters from your display name to subscribe for work item events..
        /// </summary>
        internal static string AlertSettingsDialogErrorInvalidDisplayName {
            get {
                return ResourceManager.GetString("AlertSettingsDialogErrorInvalidDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20003: Could not validate one or more e-mail addresses. Correct the e-mail addresses and try again..
        /// </summary>
        internal static string AlertSettingsDialogValidationError {
            get {
                return ResourceManager.GetString("AlertSettingsDialogValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WI{0}T - Attaching micro document / image {1}.
        /// </summary>
        internal static string AttachingMicroDocument {
            get {
                return ResourceManager.GetString("AttachingMicroDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20004: Could not find the specified file &quot;{0}&quot;. \nCheck the file name and try again..
        /// </summary>
        internal static string AttachmentAddDialogInvalidFile {
            get {
                return ResourceManager.GetString("AttachmentAddDialogInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no available builds..
        /// </summary>
        internal static string AvailableBuildNotExists {
            get {
                return ResourceManager.GetString("AvailableBuildNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no available test configuration..
        /// </summary>
        internal static string AvailableTestConfigurationNotExists {
            get {
                return ResourceManager.GetString("AvailableTestConfigurationNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no available test plan..
        /// </summary>
        internal static string AvailableTestPlanNotExists {
            get {
                return ResourceManager.GetString("AvailableTestPlanNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build: {0} is linked to testResult: {1}.
        /// </summary>
        internal static string BuildIsLinkedTo {
            get {
                return ResourceManager.GetString("BuildIsLinkedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save test steps for {0} because a previous save failed..
        /// </summary>
        internal static string CannotSaveTestSteps {
            get {
                return ResourceManager.GetString("CannotSaveTestSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W{0}: Cannot update image source for {1}. Attachment {2} not found..
        /// </summary>
        internal static string CannotUpdateImageSource {
            get {
                return ResourceManager.GetString("CannotUpdateImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration not exists. .
        /// </summary>
        internal static string ConfigurationNotExists {
            get {
                return ResourceManager.GetString("ConfigurationNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20005: Could not find the specified directory..
        /// </summary>
        internal static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter &lt;BuildAge&gt; must be a number..
        /// </summary>
        internal static string Error_BuildAgeDouble {
            get {
                return ResourceManager.GetString("Error_BuildAgeDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter &lt;BuildQualities&gt; must be inside of &lt;BuildFilters&gt;..
        /// </summary>
        internal static string Error_BuildQualityIsNotInsideBuildFilters {
            get {
                return ResourceManager.GetString("Error_BuildQualityIsNotInsideBuildFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connect to TFS.
        /// </summary>
        internal static string Error_ConnectTFS {
            get {
                return ResourceManager.GetString("Error_ConnectTFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting query hierarchy.
        /// </summary>
        internal static string Error_GetQueryHierarchy {
            get {
                return ResourceManager.GetString("Error_GetQueryHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting TFS work items.
        /// </summary>
        internal static string Error_LoadTFSWorkItems {
            get {
                return ResourceManager.GetString("Error_LoadTFSWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Query &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Error_QueryDoesNotExists_Long {
            get {
                return ResourceManager.GetString("Error_QueryDoesNotExists_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query does not exist..
        /// </summary>
        internal static string Error_QueryDoesNotExists_Short {
            get {
                return ResourceManager.GetString("Error_QueryDoesNotExists_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF210004: The control could not be loaded from the assembly..
        /// </summary>
        internal static string ErrorNoControl {
            get {
                return ResourceManager.GetString("ErrorNoControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20006: Could not save the query..
        /// </summary>
        internal static string ErrorSavingQuery {
            get {
                return ResourceManager.GetString("ErrorSavingQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension property &apos;ExpectedResult&apos; is only implemented for TestStepResults..
        /// </summary>
        internal static string ExpectedResultIsOnlyImplementedForTestStepResults {
            get {
                return ResourceManager.GetString("ExpectedResultIsOnlyImplementedForTestStepResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20007: The value for Width is not supported. Choose a Width between 0 and 65536..
        /// </summary>
        internal static string FieldChooserWidthError {
            get {
                return ResourceManager.GetString("FieldChooserWidthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20008: The value for field &apos;{0}&apos; is not supported. Specify the value as a decimal number..
        /// </summary>
        internal static string FieldControlInvalidDouble {
            get {
                return ResourceManager.GetString("FieldControlInvalidDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20009: The value for field &apos;{0}&apos; is not supported. Specify the value as a whole number between -2147483648 to 2147483647..
        /// </summary>
        internal static string FieldControlInvalidInteger {
            get {
                return ResourceManager.GetString("FieldControlInvalidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20010: The value for field &apos;{0}&apos; has unsupported characters..
        /// </summary>
        internal static string FieldStatusInvalidCharacters {
            get {
                return ResourceManager.GetString("FieldStatusInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for field &apos;{0}&apos; is computed and cannot be changed..
        /// </summary>
        internal static string FieldStatusInvalidComputedField {
            get {
                return ResourceManager.GetString("FieldStatusInvalidComputedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20001: The value for field &apos;{0}&apos; is not a recognized date..
        /// </summary>
        internal static string FieldStatusInvalidDate {
            get {
                return ResourceManager.GetString("FieldStatusInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20012: Field &apos;{0}&apos; cannot be empty..
        /// </summary>
        internal static string FieldStatusInvalidEmpty {
            get {
                return ResourceManager.GetString("FieldStatusInvalidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20013: Field &apos;{0}&apos; cannot be empty, and must be different from the original value..
        /// </summary>
        internal static string FieldStatusInvalidEmptyOrOldValue {
            get {
                return ResourceManager.GetString("FieldStatusInvalidEmptyOrOldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20014: The value for field &apos;{0}&apos; is not in a recognized format..
        /// </summary>
        internal static string FieldStatusInvalidFormat {
            get {
                return ResourceManager.GetString("FieldStatusInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20015: The field &apos;{0}&apos; contains a value that is not in the list of supported values..
        /// </summary>
        internal static string FieldStatusInvalidListValue {
            get {
                return ResourceManager.GetString("FieldStatusInvalidListValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for field &apos;{0}&apos; must be empty..
        /// </summary>
        internal static string FieldStatusInvalidNotEmpty {
            get {
                return ResourceManager.GetString("FieldStatusInvalidNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for field &apos;{0}&apos; must be empty or the same as the original value..
        /// </summary>
        internal static string FieldStatusInvalidNotEmptyOrOldValue {
            get {
                return ResourceManager.GetString("FieldStatusInvalidNotEmptyOrOldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for field &apos;{0}&apos; must be the same as the original value..
        /// </summary>
        internal static string FieldStatusInvalidNotOldValue {
            get {
                return ResourceManager.GetString("FieldStatusInvalidNotOldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is read only. You may have to change the state of the work item..
        /// </summary>
        internal static string FieldStatusInvalidNotOldValue2 {
            get {
                return ResourceManager.GetString("FieldStatusInvalidNotOldValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20016: The value for field &apos;{0}&apos; must be updated, the current value is no longer supported..
        /// </summary>
        internal static string FieldStatusInvalidOldValue {
            get {
                return ResourceManager.GetString("FieldStatusInvalidOldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20017: The area or iteration provided for field &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string FieldStatusInvalidPath {
            get {
                return ResourceManager.GetString("FieldStatusInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for field &apos;{0}&apos; is too long..
        /// </summary>
        internal static string FieldStatusInvalidTooLong {
            get {
                return ResourceManager.GetString("FieldStatusInvalidTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF207011: The value for field &apos;{0}&apos; is {1} characters long, which exceeds the maximum length of {2} characters..
        /// </summary>
        internal static string FieldStatusInvalidTooLongWithDetails {
            get {
                return ResourceManager.GetString("FieldStatusInvalidTooLongWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for field &apos;{0}&apos; is not of the right type..
        /// </summary>
        internal static string FieldStatusInvalidType {
            get {
                return ResourceManager.GetString("FieldStatusInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an unknown problem with field &apos;{0}&apos;..
        /// </summary>
        internal static string FieldStatusInvalidUnknown {
            get {
                return ResourceManager.GetString("FieldStatusInvalidUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20018: The field &apos;{0}&apos; is unsupported because of a value in another field..
        /// </summary>
        internal static string FieldStatusInvalidValueInOtherField {
            get {
                return ResourceManager.GetString("FieldStatusInvalidValueInOtherField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20019: The field &apos;{0}&apos; is unsupported because a value is missing in another field..
        /// </summary>
        internal static string FieldStatusInvalidValueNotInOtherField {
            get {
                return ResourceManager.GetString("FieldStatusInvalidValueNotInOtherField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20034: The area does not exist or you do not have permission to save work items in the area &apos;{0}&apos;. Change the value for field &apos;{1}&apos; to an area where you have write permissions..
        /// </summary>
        internal static string FieldStatusNoWritePermissionToAreaNode {
            get {
                return ResourceManager.GetString("FieldStatusNoWritePermissionToAreaNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; is valid..
        /// </summary>
        internal static string FieldStatusValidFieldStatusValid {
            get {
                return ResourceManager.GetString("FieldStatusValidFieldStatusValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20036: The macro &apos;{0}&apos; is not recognized. Available macros include @Me, @Project, and @Today..
        /// </summary>
        internal static string FilterGridInvalidMacro {
            get {
                return ResourceManager.GetString("FilterGridInvalidMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20032: The operator for row {0} is not recognized or missing..
        /// </summary>
        internal static string FilterGridOperatorMissing {
            get {
                return ResourceManager.GetString("FilterGridOperatorMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geting all test cases based on test suite ....
        /// </summary>
        internal static string GetAllTestCasesBasedOnTestSuite {
            get {
                return ResourceManager.GetString("GetAllTestCasesBasedOnTestSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting the available test configurations for given test plan....
        /// </summary>
        internal static string GetAllTestConfigurationsForTestPlan {
            get {
                return ResourceManager.GetString("GetAllTestConfigurationsForTestPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all test results that belongs to the given test case....
        /// </summary>
        internal static string GetAllTestResultsBasedOnTestCase {
            get {
                return ResourceManager.GetString("GetAllTestResultsBasedOnTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting the available assigned test configurations for test cases of given test plan....
        /// </summary>
        internal static string GetAssignedTestConfigurationsForTestCases {
            get {
                return ResourceManager.GetString("GetAssignedTestConfigurationsForTestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting the available assigned test configurations for given test plan....
        /// </summary>
        internal static string GetAssignedTestConfigurationsForTestPlan {
            get {
                return ResourceManager.GetString("GetAssignedTestConfigurationsForTestPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting a dictionary of test point IDs with latest Test Run ID.
        /// </summary>
        internal static string GetTestPointIds {
            get {
                return ResourceManager.GetString("GetTestPointIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting test points for test cases....
        /// </summary>
        internal static string GetTestPointsForTestCases {
            get {
                return ResourceManager.GetString("GetTestPointsForTestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting test points for test plan....
        /// </summary>
        internal static string GetTestPointsForTestPlan {
            get {
                return ResourceManager.GetString("GetTestPointsForTestPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting test points for test suite....
        /// </summary>
        internal static string GetTestPointsForTestSuite {
            get {
                return ResourceManager.GetString("GetTestPointsForTestSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting tfs work item by id....
        /// </summary>
        internal static string GetTfsWorkItemById {
            get {
                return ResourceManager.GetString("GetTfsWorkItemById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20022: Zero is not a supported work item ID. Enter a positive integer and try again..
        /// </summary>
        internal static string GoToWorkItemDialogZeroId {
            get {
                return ResourceManager.GetString("GoToWorkItemDialogZeroId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20024: The work item ID must be a positive integer..
        /// </summary>
        internal static string LinkDialogErrorWorkitemIdShouldBeNumeric {
            get {
                return ResourceManager.GetString("LinkDialogErrorWorkitemIdShouldBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link &apos;{0}&apos; does not support multiple linked work items. Please add one link only!.
        /// </summary>
        internal static string LinkError_OneToManyViolation {
            get {
                return ResourceManager.GetString("LinkError_OneToManyViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20026: A work item cannot contain a related link to itself..
        /// </summary>
        internal static string LinksControlCannotRelateToSelfError {
            get {
                return ResourceManager.GetString("LinksControlCannotRelateToSelfError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20027: Could not open the link..
        /// </summary>
        internal static string LinksControlErrorCouldNotToOpenLink {
            get {
                return ResourceManager.GetString("LinksControlErrorCouldNotToOpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20028: Could not open the link. The linked item may not be registered in the system..
        /// </summary>
        internal static string LinksControlInvalidArtifactUrl {
            get {
                return ResourceManager.GetString("LinksControlInvalidArtifactUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link to the work item with the id &apos;{0}&apos; could not be created, since the work item has the type &apos;{1}&apos;, which is not supported by the link definition..
        /// </summary>
        internal static string LinkWarning_WorkItemTypeViolation {
            get {
                return ResourceManager.GetString("LinkWarning_WorkItemTypeViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying TFS Work Items ....
        /// </summary>
        internal static string LoadWIs_Querying {
            get {
                return ResourceManager.GetString("LoadWIs_Querying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting and querying linked Work Items: {0} of {1}.
        /// </summary>
        internal static string LoadWIs_Sorting {
            get {
                return ResourceManager.GetString("LoadWIs_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading work items from TFS ....
        /// </summary>
        internal static string LoadWorkItems {
            get {
                return ResourceManager.GetString("LoadWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading work items by id ....
        /// </summary>
        internal static string LoadWorkItemsById {
            get {
                return ResourceManager.GetString("LoadWorkItemsById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading work items by title ....
        /// </summary>
        internal static string LoadWorkItemsByTitle {
            get {
                return ResourceManager.GetString("LoadWorkItemsByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading work items from saved query ....
        /// </summary>
        internal static string LoadWorkItemsFromSavedQuery {
            get {
                return ResourceManager.GetString("LoadWorkItemsFromSavedQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading work items without configuration ....
        /// </summary>
        internal static string LoadWorkItemsWithoutConfiguration {
            get {
                return ResourceManager.GetString("LoadWorkItemsWithoutConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mapping entry could be found for the work item type ({0}) when tried to map work item id ({1})..
        /// </summary>
        internal static string NoMappingEntryFound {
            get {
                return ResourceManager.GetString("NoMappingEntryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} associated work items..
        /// </summary>
        internal static string NumberOfAssociatedWorkItems {
            get {
                return ResourceManager.GetString("NumberOfAssociatedWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of available test plans:.
        /// </summary>
        internal static string NumberOfAvailableTestPlans {
            get {
                return ResourceManager.GetString("NumberOfAvailableTestPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of available test runs:.
        /// </summary>
        internal static string NumberOfAvailableTestRuns {
            get {
                return ResourceManager.GetString("NumberOfAvailableTestRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} associated work items match the given conditions.
        /// </summary>
        internal static string NumberOfMatchedAssociatedWorkItems {
            get {
                return ResourceManager.GetString("NumberOfMatchedAssociatedWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of test points:.
        /// </summary>
        internal static string NumberOfTestPoints {
            get {
                return ResourceManager.GetString("NumberOfTestPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} test results for test plan {1}..
        /// </summary>
        internal static string NumberOfTestResultForTestPlan {
            get {
                return ResourceManager.GetString("NumberOfTestResultForTestPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} test results..
        /// </summary>
        internal static string NumberOfTestResults {
            get {
                return ResourceManager.GetString("NumberOfTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of work items:.
        /// </summary>
        internal static string NumberOfWorkItems {
            get {
                return ResourceManager.GetString("NumberOfWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterizedString failed to replace parameter &apos;{0}&apos; in string &apos;{1}&apos; with &apos;{2}&apos;..
        /// </summary>
        internal static string ParameterizedStringFailed {
            get {
                return ResourceManager.GetString("ParameterizedStringFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse test step &apos;{0}&apos;. The string does not contain at least one element separated by {1}..
        /// </summary>
        internal static string ParsingTestStepFailed {
            get {
                return ResourceManager.GetString("ParsingTestStepFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20029: The query is not complete. Please correct and try again..
        /// </summary>
        internal static string QueryAdapterErrorInvalidFilter {
            get {
                return ResourceManager.GetString("QueryAdapterErrorInvalidFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing parameters in string &apos;{0}&apos; - {1}.
        /// </summary>
        internal static string ReplacingParameters {
            get {
                return ResourceManager.GetString("ReplacingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching all linked work items for test result associated to test case:{0}.
        /// </summary>
        internal static string SearchAllLinkedWorkItemsForTestResult {
            get {
                return ResourceManager.GetString("SearchAllLinkedWorkItemsForTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search builds for test case: {0} with latestTestResults set to: {1} and latestTestResultsForAllConfigurations set to: {2}.
        /// </summary>
        internal static string SearchBuildsForTestCase {
            get {
                return ResourceManager.GetString("SearchBuildsForTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching test suite by name ....
        /// </summary>
        internal static string SearchingTestSuiteByName {
            get {
                return ResourceManager.GetString("SearchingTestSuiteByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching test suite by path....
        /// </summary>
        internal static string SearchingTestSuiteByPath {
            get {
                return ResourceManager.GetString("SearchingTestSuiteByPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test cases for given test plan not exist..
        /// </summary>
        internal static string TestCasesForTestPlanNotExist {
            get {
                return ResourceManager.GetString("TestCasesForTestPlanNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given test configuration not exists..
        /// </summary>
        internal static string TestConfigurationNotExists {
            get {
                return ResourceManager.GetString("TestConfigurationNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given test plan not exists..
        /// </summary>
        internal static string TestPlanNotExists {
            get {
                return ResourceManager.GetString("TestPlanNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to access property &apos;{0}&apos; of object &apos;{1}&apos;..
        /// </summary>
        internal static string TestReport_DetermineValueFailed {
            get {
                return ResourceManager.GetString("TestReport_DetermineValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test suite with the name &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string TestSuiteNameCouldNotBeFound {
            get {
                return ResourceManager.GetString("TestSuiteNameCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given test suite not exists..
        /// </summary>
        internal static string TestSuiteNotExist {
            get {
                return ResourceManager.GetString("TestSuiteNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test suite path &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string TestSuitePathCouldNotBeFound {
            get {
                return ResourceManager.GetString("TestSuitePathCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured when searching a test suite via  tree path..
        /// </summary>
        internal static string TestSuiteSearchError {
            get {
                return ResourceManager.GetString("TestSuiteSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test suites not exist..
        /// </summary>
        internal static string TestSuitesNotExist {
            get {
                return ResourceManager.GetString("TestSuitesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Field.
        /// </summary>
        internal static string UnknownField {
            get {
                return ResourceManager.GetString("UnknownField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF20033: You do not have permission to modify work items in the area &apos;{0}&apos;. Contact your Team Foundation System administrator..
        /// </summary>
        internal static string WorkItemErrorNoWritePermission {
            get {
                return ResourceManager.GetString("WorkItemErrorNoWritePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item {0} not available..
        /// </summary>
        internal static string WorkItemIsNotAvailable {
            get {
                return ResourceManager.GetString("WorkItemIsNotAvailable", resourceCulture);
            }
        }
    }
}
