//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIT.TFS.SyncService.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIT.TFS.SyncService.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Work Item(s) not shown..
        /// </summary>
        public static string AmountOfWorkItemsNotShown {
            get {
                return ResourceManager.GetString("AmountOfWorkItemsNotShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hyperlink base of this document is different from the document attachment folder. In order for relative attachment links to work, the hyperlink base needs to point to the document attachment location.
        ///
        ///If you continue, the hyperlink base will be adjusted automatically. Do you want to continue?.
        /// </summary>
        public static string Attachment_AdjustHyperlinkBase {
            get {
                return ResourceManager.GetString("Attachment_AdjustHyperlinkBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document contains links to downloaded attachments. These links only work if the attachment folder is in the same folder as the document. Please make sure to copy or move the attachment folder to the new document location..
        /// </summary>
        public static string Attachment_SaveAsWarning {
            get {
                return ResourceManager.GetString("Attachment_SaveAsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to download attachments, the document location must be known. Do you want to save the document now?.
        /// </summary>
        public static string Attachment_SaveDocumentNowText {
            get {
                return ResourceManager.GetString("Attachment_SaveDocumentNowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the folder containing custom templates..
        /// </summary>
        public static string BrowserDialogDescription {
            get {
                return ResourceManager.GetString("BrowserDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if WordToTFSConsole is activated....
        /// </summary>
        public static string CheckIfConsoleIsActivated {
            get {
                return ResourceManager.GetString("CheckIfConsoleIsActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a configuration file is specified, it is not allowed to specify basic settings by command line parameters. You can use either the command line parameters or the configuration file for the specification of basic settings..
        /// </summary>
        public static string CommandArgumentsError {
            get {
                return ResourceManager.GetString("CommandArgumentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item {0} is missing in your configuration file..
        /// </summary>
        public static string ConfigurationFileMisconfigured {
            get {
                return ResourceManager.GetString("ConfigurationFileMisconfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified configuration file does not exist..
        /// </summary>
        public static string ConfigurationFileNotExistsError {
            get {
                return ResourceManager.GetString("ConfigurationFileNotExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsoleExtension is activated..
        /// </summary>
        public static string ConsoleIsActivated {
            get {
                return ResourceManager.GetString("ConsoleIsActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsoleExtension is not activated..
        /// </summary>
        public static string ConsoleIsNotActivated {
            get {
                return ResourceManager.GetString("ConsoleIsNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating hyperlinks....
        /// </summary>
        public static string CreateHyperlinks {
            get {
                return ResourceManager.GetString("CreateHyperlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating model ....
        /// </summary>
        public static string CreateModelInfo {
            get {
                return ResourceManager.GetString("CreateModelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating report by area path ....
        /// </summary>
        public static string CreateReportByAreaPath {
            get {
                return ResourceManager.GetString("CreateReportByAreaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating report by iteration path ....
        /// </summary>
        public static string CreateReportByIterationPath {
            get {
                return ResourceManager.GetString("CreateReportByIterationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating report by test plan hierarchy ....
        /// </summary>
        public static string CreateReportByTestPlanHierarchy {
            get {
                return ResourceManager.GetString("CreateReportByTestPlanHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating test result report ....
        /// </summary>
        public static string CreateReportInfo {
            get {
                return ResourceManager.GetString("CreateReportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating test result document....
        /// </summary>
        public static string CreateTestResultDoc {
            get {
                return ResourceManager.GetString("CreateTestResultDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating test sprecification document....
        /// </summary>
        public static string CreateTestSpecificationDoc {
            get {
                return ResourceManager.GetString("CreateTestSpecificationDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIT GmbH &amp; Co. KG.
        /// </summary>
        public static string DefaultTemplateBundleName {
            get {
                return ResourceManager.GetString("DefaultTemplateBundleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running work item query....
        /// </summary>
        public static string DoFindProccessMessage {
            get {
                return ResourceManager.GetString("DoFindProccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped creation of summary page and processing post operations because of error or cancellation..
        /// </summary>
        public static string DoImportError {
            get {
                return ResourceManager.GetString("DoImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; is not found in source folder..
        /// </summary>
        public static string Error_LoadOfTemplateComponentFailed {
            get {
                return ResourceManager.GetString("Error_LoadOfTemplateComponentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading the TFS Team Explorer plugin. Please check the system requirements and make sure that you have the matching version of it installed..
        /// </summary>
        public static string Error_TeamPickerFailed_Long {
            get {
                return ResourceManager.GetString("Error_TeamPickerFailed_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during connection to TFS.
        /// </summary>
        public static string Error_TeamPickerFailed_Short {
            get {
                return ResourceManager.GetString("Error_TeamPickerFailed_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Word template: {0} does not exist..
        /// </summary>
        public static string Error_TemplateDoesNotExist {
            get {
                return ResourceManager.GetString("Error_TemplateDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default connection settings from your template configuration are wrong or your TFS cannot be reached..
        /// </summary>
        public static string Error_Wrong_Connection_Long {
            get {
                return ResourceManager.GetString("Error_Wrong_Connection_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong connection settings.
        /// </summary>
        public static string Error_Wrong_Connection_Short {
            get {
                return ResourceManager.GetString("Error_Wrong_Connection_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception message: {0}. StackTrace: {1}..
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit the console..
        /// </summary>
        public static string ExitInformation {
            get {
                return ResourceManager.GetString("ExitInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended the PATH with %{0}%.
        /// </summary>
        public static string ExtendedPath {
            get {
                return ResourceManager.GetString("ExtendedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file where to store the report already exists. Either set the overwrite option to true or specify another file name..
        /// </summary>
        public static string FileExistsError {
            get {
                return ResourceManager.GetString("FileExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist or can be overwritten..
        /// </summary>
        public static string FileIsOverwrittenOrNotExists {
            get {
                return ResourceManager.GetString("FileIsOverwrittenOrNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path where to store the document was not specified..
        /// </summary>
        public static string FilenameNotSpecifiedError {
            get {
                return ResourceManager.GetString("FilenameNotSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document has been saved to {0}.
        /// </summary>
        public static string FileSavedInformation {
            get {
                return ResourceManager.GetString("FileSavedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test results filtered: Original Size {0}. New Size {1}.
        /// </summary>
        public static string FilterTestResults {
            get {
                return ResourceManager.GetString("FilterTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkItems filtered: Original Size {0}. New Size {1}.
        /// </summary>
        public static string FilterWorkItems {
            get {
                return ResourceManager.GetString("FilterWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalization of document....
        /// </summary>
        public static string FinalizationOfDoc {
            get {
                return ResourceManager.GetString("FinalizationOfDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding work items finished..
        /// </summary>
        public static string FindFinished {
            get {
                return ResourceManager.GetString("FindFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding work items ....
        /// </summary>
        public static string FindWorkItems {
            get {
                return ResourceManager.GetString("FindWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all linked builds for a test management object.....
        /// </summary>
        public static string GetBuildsForTestManagmentObject {
            get {
                return ResourceManager.GetString("GetBuildsForTestManagmentObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Linked Configurations for a test management object....
        /// </summary>
        public static string GetLinkedConfigurationForTestManagementObject {
            get {
                return ResourceManager.GetString("GetLinkedConfigurationForTestManagementObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all linked TestCases for a test management object....
        /// </summary>
        public static string GetLinkedTestCasesForTestManagmentObject {
            get {
                return ResourceManager.GetString("GetLinkedTestCasesForTestManagmentObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all Linked Test Results for a test management object....
        /// </summary>
        public static string GetLinkedTestResultsForTestManagmentObject {
            get {
                return ResourceManager.GetString("GetLinkedTestResultsForTestManagmentObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all linked work items for a test management object....
        /// </summary>
        public static string GetLinkedWorkItemsForTestManagementObject {
            get {
                return ResourceManager.GetString("GetLinkedWorkItemsForTestManagementObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting the PATH variable and the ClickOnce Location....
        /// </summary>
        public static string GetPath {
            get {
                return ResourceManager.GetString("GetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting work items by ids..
        /// </summary>
        public static string GetWorkItemById {
            get {
                return ResourceManager.GetString("GetWorkItemById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the characters you entered into &apos;IDs&apos; text field are in wrong format. Please type an ID containing only numbers (0-9), spaces, and list separators (&apos;;&apos; or &apos;,&apos;). .
        /// </summary>
        public static string GetWorkItems_Error_WrongIDs {
            get {
                return ResourceManager.GetString("GetWorkItems_Error_WrongIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Work Items.
        /// </summary>
        public static string GetWorkItems_Title {
            get {
                return ResourceManager.GetString("GetWorkItems_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting work items by query name..
        /// </summary>
        public static string GetWorkItemsByQueryName {
            get {
                return ResourceManager.GetString("GetWorkItemsByQueryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing work items finished..
        /// </summary>
        public static string ImportFinished {
            get {
                return ResourceManager.GetString("ImportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing work items....
        /// </summary>
        public static string ImportWorkItems {
            get {
                return ResourceManager.GetString("ImportWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization of document....
        /// </summary>
        public static string InitializationOfDocument {
            get {
                return ResourceManager.GetString("InitializationOfDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization of file name with time stamp....
        /// </summary>
        public static string InitializationOfFileName {
            get {
                return ResourceManager.GetString("InitializationOfFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} template bundles..
        /// </summary>
        public static string LoadTemplateBundles {
            get {
                return ResourceManager.GetString("LoadTemplateBundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading template information from {0}.
        /// </summary>
        public static string LoadTemplateInfo {
            get {
                return ResourceManager.GetString("LoadTemplateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClickOnceLocation: {0}.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordToTFS Plugin.
        /// </summary>
        public static string MessageBox_Title {
            get {
                return ResourceManager.GetString("MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New PATH is %{0}%.
        /// </summary>
        public static string NewPath {
            get {
                return ResourceManager.GetString("NewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoneResolutionState {
            get {
                return ResourceManager.GetString("NoneResolutionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no work items found for your arguments..
        /// </summary>
        public static string NoWorkItemsFoundInformation {
            get {
                return ResourceManager.GetString("NoWorkItemsFoundInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of all test cases:.
        /// </summary>
        public static string NumberOfAllTestCases {
            get {
                return ResourceManager.GetString("NumberOfAllTestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of found work items during importing:.
        /// </summary>
        public static string NumberOfFoundWorkItems {
            get {
                return ResourceManager.GetString("NumberOfFoundWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of test cases of test suite:.
        /// </summary>
        public static string NumberOfTestCasesBasedOnSuite {
            get {
                return ResourceManager.GetString("NumberOfTestCasesBasedOnSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no option specified how to get work items..
        /// </summary>
        public static string OptionsNullError {
            get {
                return ResourceManager.GetString("OptionsNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify either the option &quot;WorkItemIDs&quot; or the option WorkItemQuery..
        /// </summary>
        public static string OptionsNullErrorInstruction {
            get {
                return ResourceManager.GetString("OptionsNullErrorInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was specified to get work items by id and by query. Only one of these two options can be chosen..
        /// </summary>
        public static string OptionsOverloadedError {
            get {
                return ResourceManager.GetString("OptionsOverloadedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is: {0}.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation path of the WordToTFS Add-in cannot be determined..
        /// </summary>
        public static string PathCanNotBeDetermined {
            get {
                return ResourceManager.GetString("PathCanNotBeDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print out all test results....
        /// </summary>
        public static string PrintTestResults {
            get {
                return ResourceManager.GetString("PrintTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project was not specified..
        /// </summary>
        public static string ProjectNotSpecifiedError {
            get {
                return ResourceManager.GetString("ProjectNotSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Work Items.
        /// </summary>
        public static string QueryWorkItems_Title {
            get {
                return ResourceManager.GetString("QueryWorkItems_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file is about being read in..
        /// </summary>
        public static string ReadConfigurationInformation {
            get {
                return ResourceManager.GetString("ReadConfigurationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register services....
        /// </summary>
        public static string RegisterServices {
            get {
                return ResourceManager.GetString("RegisterServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is an unsupported FieldValueType in the current context..
        /// </summary>
        public static string ReplaceFieldValueTypeNotSupported {
            get {
                return ResourceManager.GetString("ReplaceFieldValueTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; of the variable name of replacment &apos;{1}&apos; contains an unknown system variable name..
        /// </summary>
        public static string ReplaceUnknownSystemVariableName {
            get {
                return ResourceManager.GetString("ReplaceUnknownSystemVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; of the variable name of replacment &apos;{1}&apos; contains an unknown variable name. Variable must be defined in your template..
        /// </summary>
        public static string ReplaceUnknownVariableName {
            get {
                return ResourceManager.GetString("ReplaceUnknownVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation of the report failed..
        /// </summary>
        public static string ReportCreationFailed {
            get {
                return ResourceManager.GetString("ReportCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report was created..
        /// </summary>
        public static string ReportCreationSuccessfull {
            get {
                return ResourceManager.GetString("ReportCreationSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server was not specified..
        /// </summary>
        public static string ServerNotSpecifiedError {
            get {
                return ResourceManager.GetString("ServerNotSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services are null..
        /// </summary>
        public static string ServicesNotExists {
            get {
                return ResourceManager.GetString("ServicesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the environment variable %{0}% to: {1}.
        /// </summary>
        public static string SetEnvironmentVariable {
            get {
                return ResourceManager.GetString("SetEnvironmentVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suite {0} cannot be found. Fallback to root suite of current plan {1}..
        /// </summary>
        public static string SuiteNotFound {
            get {
                return ResourceManager.GetString("SuiteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template bundle {0} at {1} not available. Loading cached version..
        /// </summary>
        public static string TemplateBundleNotAvailable {
            get {
                return ResourceManager.GetString("TemplateBundleNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WordToTFS-template which should be used was not specified..
        /// </summary>
        public static string TemplateNotSpecifiedError {
            get {
                return ResourceManager.GetString("TemplateNotSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemplateBundles or Templates have changed..
        /// </summary>
        public static string TemplatesChanged {
            get {
                return ResourceManager.GetString("TemplatesChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test plan or test suite not exists..
        /// </summary>
        public static string TestPlanOrSuiteNotExist {
            get {
                return ResourceManager.GetString("TestPlanOrSuiteNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_{1}.
        /// </summary>
        public static string TestReportHelper_AttachmentFilename {
            get {
                return ResourceManager.GetString("TestReportHelper_AttachmentFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string TestReportHelper_WorkItemViewLink_AutoText {
            get {
                return ResourceManager.GetString("TestReportHelper_WorkItemViewLink_AutoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string TestResult_AllConfigurations {
            get {
                return ResourceManager.GetString("TestResult_AllConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string TestResult_AllServerBuilds {
            get {
                return ResourceManager.GetString("TestResult_AllServerBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test result error.
        /// </summary>
        public static string TestResult_Error {
            get {
                return ResourceManager.GetString("TestResult_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled by user..
        /// </summary>
        public static string TestResult_OperationCancelled {
            get {
                return ResourceManager.GetString("TestResult_OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no option specified where to place the test configuration information. The available options are &quot;AboveTestPlan&quot;, &quot;BeneathTestPlan&quot;, &quot;BeneathTestSuites&quot; or &quot;BeneathFirstTestSuite&quot;..
        /// </summary>
        public static string TestSettingsConfigurationPositionError {
            get {
                return ResourceManager.GetString("TestSettingsConfigurationPositionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no option specified how to create the document structure. The available options are &quot;IterationPath&quot;, &quot;AreaPath&quot; or &quot;TestPlanHierarchy&quot;..
        /// </summary>
        public static string TestSettingsDocumentStructureError {
            get {
                return ResourceManager.GetString("TestSettingsDocumentStructureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please adapt the configuration file properly..
        /// </summary>
        public static string TestSettingsErrorInstruction {
            get {
                return ResourceManager.GetString("TestSettingsErrorInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option specified where to place the test configuration information is not valid. The available options are &quot;AboveTestPlan&quot;, &quot;BeneathTestPlan&quot;, &quot;BeneathTestSuites&quot; or &quot;BeneathFirstTestSuite&quot;..
        /// </summary>
        public static string TestSettingsInvalidConfigurationPositionError {
            get {
                return ResourceManager.GetString("TestSettingsInvalidConfigurationPositionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option specified how to create the document structure is not valid. The available options are &quot;IterationPath&quot;, &quot;AreaPath&quot; or &quot;TestPlanHierarchy&quot;..
        /// </summary>
        public static string TestSettingsInvalidDocumentStructureError {
            get {
                return ResourceManager.GetString("TestSettingsInvalidDocumentStructureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option specified how to sort the cases is not valid. cases. The available options are &quot;IterationPath&quot;, &quot;AreaPath&quot; or &quot;WorkItemId&quot;..
        /// </summary>
        public static string TestSettingsInvalidTestCasesSortError {
            get {
                return ResourceManager.GetString("TestSettingsInvalidTestCasesSortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified test plan does not exist..
        /// </summary>
        public static string TestSettingsInvalidTestPlan {
            get {
                return ResourceManager.GetString("TestSettingsInvalidTestPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified test suite does not exist..
        /// </summary>
        public static string TestSettingsInvalidTestSuite {
            get {
                return ResourceManager.GetString("TestSettingsInvalidTestSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test suite for the specified suite path could not be determined..
        /// </summary>
        public static string TestSettingsInvalidTestSuitePath {
            get {
                return ResourceManager.GetString("TestSettingsInvalidTestSuitePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no option specified how to sort the test cases. The available options are &quot;IterationPath&quot;, &quot;AreaPath&quot; or &quot;WorkItemId&quot;..
        /// </summary>
        public static string TestSettingsTestCasesSortError {
            get {
                return ResourceManager.GetString("TestSettingsTestCasesSortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no test plan specified in the configuration file..
        /// </summary>
        public static string TestSettingsTestPlanError {
            get {
                return ResourceManager.GetString("TestSettingsTestPlanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test specification error.
        /// </summary>
        public static string TestSpecification_Error {
            get {
                return ResourceManager.GetString("TestSpecification_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document contains already some of the Work Items to import. Your changes on these Work Items will get lost. Do you want to proceed?&quot;.
        /// </summary>
        public static string TFSExport_ExistingWorkItems {
            get {
                return ResourceManager.GetString("TFSExport_ExistingWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder contains subfolders. Do you want to set this folder as project mapped template source? 
        ///
        ///Templates in a project mapped template source will only be available if the user is connected to a project as defined by the subfolder structure..
        /// </summary>
        public static string TM_AddTemplateBundleAsProjectMappedHierarchy {
            get {
                return ResourceManager.GetString("TM_AddTemplateBundleAsProjectMappedHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete template.
        /// </summary>
        public static string TM_ConfirmDeleteHeader {
            get {
                return ResourceManager.GetString("TM_ConfirmDeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the template &apos;{0}&apos;?.
        /// </summary>
        public static string TM_ConfirmDeleteText {
            get {
                return ResourceManager.GetString("TM_ConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordToTFSVaribaleNameIs: {0}.
        /// </summary>
        public static string VariableName {
            get {
                return ResourceManager.GetString("VariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document and Word have been closed.
        /// </summary>
        public static string WordClosed {
            get {
                return ResourceManager.GetString("WordClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word document is saved..
        /// </summary>
        public static string WordDocSaveMessage {
            get {
                return ResourceManager.GetString("WordDocSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select the check box for at least one type of link or click &apos;Return links of any types&apos;..
        /// </summary>
        public static string WordToTFS_Error_LinkTypesNotSelected {
            get {
                return ResourceManager.GetString("WordToTFS_Error_LinkTypesNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to start import process because the cursor position is located inside of table. Nested tables are not allowed. 
        ///Please move the cursor position outside of the table..
        /// </summary>
        public static string WordToTFS_Error_TableInsertInTable {
            get {
                return ResourceManager.GetString("WordToTFS_Error_TableInsertInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordToTFS.exe cannot be found under {0}, skipping the adjustment of the path variables..
        /// </summary>
        public static string WordToTFSNotFound {
            get {
                return ResourceManager.GetString("WordToTFSNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding work items finished..
        /// </summary>
        public static string WorkItemsAreFound {
            get {
                return ResourceManager.GetString("WorkItemsAreFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing work items finished..
        /// </summary>
        public static string WorkItemsAreImported {
            get {
                return ResourceManager.GetString("WorkItemsAreImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of found work items:.
        /// </summary>
        public static string WorkItemsCountInformation {
            get {
                return ResourceManager.GetString("WorkItemsCountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All work items were imported to the document..
        /// </summary>
        public static string WorkItemsImportedInformation {
            get {
                return ResourceManager.GetString("WorkItemsImportedInformation", resourceCulture);
            }
        }
    }
}
