//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIT.TFS.SyncService.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIT.TFS.SyncService.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a configuration file is specified, it is not allowed to specify basic settings by command line parameters. You can use either the command line parameters or the configuration file for the specification of basic settings..
        /// </summary>
        internal static string CommandArgumentsError {
            get {
                return ResourceManager.GetString("CommandArgumentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WI{0}T - Comparing current value {1} with new value {2} (IgnoreFormatting={3}).
        /// </summary>
        internal static string CompareValues {
            get {
                return ResourceManager.GetString("CompareValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item {0} is missing in your configuration file..
        /// </summary>
        internal static string ConfigurationFileMisconfigured {
            get {
                return ResourceManager.GetString("ConfigurationFileMisconfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified configuration file does not exist..
        /// </summary>
        internal static string ConfigurationFileNotExistsError {
            get {
                return ResourceManager.GetString("ConfigurationFileNotExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified configuration file does not exist..
        /// </summary>
        internal static string ConfigurationFileNotExistsError1 {
            get {
                return ResourceManager.GetString("ConfigurationFileNotExistsError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WI{0}W - Creating new work item.
        /// </summary>
        internal static string CreateWorkItem {
            get {
                return ResourceManager.GetString("CreateWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new work item in tfs&quot;.
        /// </summary>
        internal static string CreateWorkItemInTFS {
            get {
                return ResourceManager.GetString("CreateWorkItemInTFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WI{0} - Creating links to other work items on tfs.
        /// </summary>
        internal static string CreatingLinksForItemsOnTFS {
            get {
                return ResourceManager.GetString("CreatingLinksForItemsOnTFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WI{0} - Creating links for word work item.
        /// </summary>
        internal static string CreatingLinksForWordWorkItem {
            get {
                return ResourceManager.GetString("CreatingLinksForWordWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WI{0} - Creating links of type {1}. New ID&apos;s={2}.
        /// </summary>
        internal static string CreatingLinksOfType {
            get {
                return ResourceManager.GetString("CreatingLinksOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WI{0}W - Deleting links of type {1}.
        /// </summary>
        internal static string DeletingLinksOfType {
            get {
                return ResourceManager.GetString("DeletingLinksOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is read only. You may have to change the state of the work item..
        /// </summary>
        internal static string FieldStatusInvalidNotOldValue2 {
            get {
                return ResourceManager.GetString("FieldStatusInvalidNotOldValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path where to store the document was not specified..
        /// </summary>
        internal static string FilenameNotSpecifiedError {
            get {
                return ResourceManager.GetString("FilenameNotSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing Work Items ....
        /// </summary>
        internal static string GetWorkItems_Importing {
            get {
                return ResourceManager.GetString("GetWorkItems_Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing Work Items {0} of {1}.
        /// </summary>
        internal static string GetWorkItems_ImportingOf {
            get {
                return ResourceManager.GetString("GetWorkItems_ImportingOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Word ....
        /// </summary>
        internal static string LO_Publish_01_OpenWord {
            get {
                return ResourceManager.GetString("LO_Publish_01_OpenWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Team Project….
        /// </summary>
        internal static string LO_Publish_02_OpenTFS {
            get {
                return ResourceManager.GetString("LO_Publish_02_OpenTFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing Work Items ....
        /// </summary>
        internal static string LO_Publish_03_SyncToTFS {
            get {
                return ResourceManager.GetString("LO_Publish_03_SyncToTFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing Work Items {0} of {1}.
        /// </summary>
        internal static string LO_Publish_03_SyncToTFSOf {
            get {
                return ResourceManager.GetString("LO_Publish_03_SyncToTFSOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to TFS ....
        /// </summary>
        internal static string LO_Publish_04_SaveToTFS {
            get {
                return ResourceManager.GetString("LO_Publish_04_SaveToTFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Work Items ....
        /// </summary>
        internal static string LO_Publish_05_SyncToWord {
            get {
                return ResourceManager.GetString("LO_Publish_05_SyncToWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Work Items {0} of {1}.
        /// </summary>
        internal static string LO_Publish_05_SyncToWordOf {
            get {
                return ResourceManager.GetString("LO_Publish_05_SyncToWordOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to Word ....
        /// </summary>
        internal static string LO_Publish_06_SaveToWord {
            get {
                return ResourceManager.GetString("LO_Publish_06_SaveToWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading file &apos;{0}&apos;.
        /// </summary>
        internal static string LogService_LoadFile {
            get {
                return ResourceManager.GetString("LogService_LoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; does not exist.
        /// </summary>
        internal static string LogService_LoadFile_FileDoesNotExist {
            get {
                return ResourceManager.GetString("LogService_LoadFile_FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading work item from &apos;{0}&apos;. Failed to load work item. Reset to default values..
        /// </summary>
        internal static string LogService_LoadFile_ResetToStandard {
            get {
                return ResourceManager.GetString("LogService_LoadFile_ResetToStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing work item &apos;{0}&apos;.
        /// </summary>
        internal static string LogService_LoadWorkItem {
            get {
                return ResourceManager.GetString("LogService_LoadWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0} converters for work item &apos;{1}&apos;.
        /// </summary>
        internal static string LogService_LoadWorkItem_Converters {
            get {
                return ResourceManager.GetString("LogService_LoadWorkItem_Converters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find image file &apos;{0}&apos;, loading standard image instead.
        /// </summary>
        internal static string LogService_LoadWorkItem_ImageFileNotFound {
            get {
                return ResourceManager.GetString("LogService_LoadWorkItem_ImageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS synchronization complete.
        /// </summary>
        internal static string LogService_Sync_Finished {
            get {
                return ResourceManager.GetString("LogService_Sync_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing TFS synchronization.
        /// </summary>
        internal static string LogService_Sync_Init {
            get {
                return ResourceManager.GetString("LogService_Sync_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing WordToTFS to TFS synchronization.
        /// </summary>
        internal static string LogService_Sync_InitForwardSync {
            get {
                return ResourceManager.GetString("LogService_Sync_InitForwardSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing of synchronization for linked work items.
        /// </summary>
        internal static string LogService_Sync_InitLinkedItems {
            get {
                return ResourceManager.GetString("LogService_Sync_InitLinkedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing TFS to WordToTFS synchronization.
        /// </summary>
        internal static string LogService_Sync_InitReverseSync {
            get {
                return ResourceManager.GetString("LogService_Sync_InitReverseSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization of work item  [{0}] failed.
        /// </summary>
        internal static string LogService_Sync_SynchronizationFailed {
            get {
                return ResourceManager.GetString("LogService_Sync_SynchronizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization of work item  [{0}] successful.
        /// </summary>
        internal static string LogService_Sync_SynchronizationSuccessful {
            get {
                return ResourceManager.GetString("LogService_Sync_SynchronizationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite={0} .
        /// </summary>
        internal static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WI{0}W - Overwriting invalid converter value with new value {1}.
        /// </summary>
        internal static string OverwritingInvalidConverter {
            get {
                return ResourceManager.GetString("OverwritingInvalidConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WI{0}W - Overwriting old value {1} with new value {2}.
        /// </summary>
        internal static string OverwritingOldwithNewValue {
            get {
                return ResourceManager.GetString("OverwritingOldwithNewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WI{0}T - Overwriting current value with new value.
        /// </summary>
        internal static string OverwritingWithNewValue {
            get {
                return ResourceManager.GetString("OverwritingWithNewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project was not specified..
        /// </summary>
        internal static string ProjectNotSpecifiedError {
            get {
                return ResourceManager.GetString("ProjectNotSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing cancelled.
        /// </summary>
        internal static string Publish_Canceled {
            get {
                return ResourceManager.GetString("Publish_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish process cancelled by user..
        /// </summary>
        internal static string Publish_Canceled_Desc {
            get {
                return ResourceManager.GetString("Publish_Canceled_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item successfully published..
        /// </summary>
        internal static string Publish_OK {
            get {
                return ResourceManager.GetString("Publish_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item skipped because it has no pending changes..
        /// </summary>
        internal static string Publish_Skipped {
            get {
                return ResourceManager.GetString("Publish_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; contains inline shapes but no text. A field with inline shapes must also contain text in order to export correctly. You can configure WordToTFS to automatically add a space in this situation. For further information please see the user manual..
        /// </summary>
        internal static string PublishErrorInlineShapes {
            get {
                return ResourceManager.GetString("PublishErrorInlineShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; of the variable name of field &apos;{1}&apos; contains an unknown system variable name..
        /// </summary>
        internal static string PublishUnknownSystemVariableName {
            get {
                return ResourceManager.GetString("PublishUnknownSystemVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; contains an image that is downscaled from its original size. Image quality might deteriorate when publishing..
        /// </summary>
        internal static string PublishWarningDownscaledImages {
            get {
                return ResourceManager.GetString("PublishWarningDownscaledImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create automatic link because the found work item of type &apos;{0}&apos; has no field &apos;{1}&apos;..
        /// </summary>
        internal static string PublishWarningMissingSubtypeField {
            get {
                return ResourceManager.GetString("PublishWarningMissingSubtypeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create automatic link because the found link target &apos;{0}&apos; is new and not published. Please publish the work item &apos;{0}&apos; first or publish the whole document..
        /// </summary>
        internal static string PublishWarningNewAutoLinkTarget {
            get {
                return ResourceManager.GetString("PublishWarningNewAutoLinkTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create automatic link because no matching work item was found..
        /// </summary>
        internal static string PublishWarningNoTarget {
            get {
                return ResourceManager.GetString("PublishWarningNoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; contains an inline shape but the field is configured to publish only text. The inline shape will not be synchronized with tfs. Please see the user manual on how to configure fields to publish as HTML or as attached documents..
        /// </summary>
        internal static string PublishWarningPlaintextInlineShapes {
            get {
                return ResourceManager.GetString("PublishWarningPlaintextInlineShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end of the cell &apos;{0}&apos; is a list item. This list item would not be exported correctly. Add an empty line below the list to solve this issue..
        /// </summary>
        internal static string PublishWarningUnclosedLists {
            get {
                return ResourceManager.GetString("PublishWarningUnclosedLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish {0} work items: {1}.
        /// </summary>
        internal static string PublishWorkItems {
            get {
                return ResourceManager.GetString("PublishWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh {0} work items: {1}.
        /// </summary>
        internal static string RefreshInfo {
            get {
                return ResourceManager.GetString("RefreshInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server was not specified..
        /// </summary>
        internal static string ServerNotSpecifiedError {
            get {
                return ResourceManager.GetString("ServerNotSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WI{0} - Synchronizing field {1}: FieldDirection={2}, ValueType={3}, HandleAsDocument={4}, DocumentMode={5}.
        /// </summary>
        internal static string SynchronizationOfField {
            get {
                return ResourceManager.GetString("SynchronizationOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WI{0} - Synchronizing work item. Direction:{1}.
        /// </summary>
        internal static string SynchronizationOfWorkItem {
            get {
                return ResourceManager.GetString("SynchronizationOfWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing work item {0} to TFS.
        /// </summary>
        internal static string SynchronizationOfWorkItemToTFS {
            get {
                return ResourceManager.GetString("SynchronizationOfWorkItemToTFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing work item {0} to word.
        /// </summary>
        internal static string SynchronizationOfWorkItemToWord {
            get {
                return ResourceManager.GetString("SynchronizationOfWorkItemToWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization of field with static content was skipped.
        /// </summary>
        internal static string SynchronizationStaticSkipped {
            get {
                return ResourceManager.GetString("SynchronizationStaticSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating links for work item {0}.
        /// </summary>
        internal static string SynchronizingLinks {
            get {
                return ResourceManager.GetString("SynchronizingLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WordToTFS-template which should be used was not specified..
        /// </summary>
        internal static string TemplateNotSpecifiedError {
            get {
                return ResourceManager.GetString("TemplateNotSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the &apos;{0}&apos; field to ensure that it can be properly saved into TFS field..
        /// </summary>
        internal static string TextFormating_FieldDetail {
            get {
                return ResourceManager.GetString("TextFormating_FieldDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; for field &apos;{1}&apos; cannot be converted because the value is not supported. Possible values: {2}..
        /// </summary>
        internal static string TextFormating_NoRequiredValueInConverter {
            get {
                return ResourceManager.GetString("TextFormating_NoRequiredValueInConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item could not be synchronized because of revision conflicts for:
        ///{0}.
        /// </summary>
        internal static string TFSError_ConflictingChanges {
            get {
                return ResourceManager.GetString("TFSError_ConflictingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS batch save operation failed.
        /// </summary>
        internal static string TFSError_TFS_save_failed {
            get {
                return ResourceManager.GetString("TFSError_TFS_save_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update dropdown list entries because the field is PublishOnly and the current value is not contained in the updated list..
        /// </summary>
        internal static string UpdateDropdownFailed {
            get {
                return ResourceManager.GetString("UpdateDropdownFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1}].
        /// </summary>
        internal static string UserInformation_Header {
            get {
                return ResourceManager.GetString("UserInformation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}... [{1}].
        /// </summary>
        internal static string UserInformation_HeaderShort {
            get {
                return ResourceManager.GetString("UserInformation_HeaderShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create new work item of type &apos;{0}&apos;.
        /// </summary>
        internal static string WorkItemSyncService_FailedToCreateNewWorkItem {
            get {
                return ResourceManager.GetString("WorkItemSyncService_FailedToCreateNewWorkItem", resourceCulture);
            }
        }
    }
}
