//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIT.TFS.SyncService.View.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIT.TFS.SyncService.View.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current installation folder of WordToTFS will be added to your PATH environment variable. Do you want to continue?.
        /// </summary>
        internal static string ConsoleExtensionInstallationInfo {
            get {
                return ResourceManager.GetString("ConsoleExtensionInstallationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to activate the Debug Log for WordToTFS. These LogFiles will contain the description of your Work Items. If these Work Items contain confidential data, make sure to delete the Log Files afterwards..
        /// </summary>
        internal static string DebugLogInfo {
            get {
                return ResourceManager.GetString("DebugLogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Path.
        /// </summary>
        internal static string DocumentStructureType_AreaPath {
            get {
                return ResourceManager.GetString("DocumentStructureType_AreaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration Path.
        /// </summary>
        internal static string DocumentStructureType_IterationPath {
            get {
                return ResourceManager.GetString("DocumentStructureType_IterationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Plan Hierarchy.
        /// </summary>
        internal static string DocumentStructureType_TestPlanHierarchy {
            get {
                return ResourceManager.GetString("DocumentStructureType_TestPlanHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing initialized.
        /// </summary>
        internal static string Info_PublishInit {
            get {
                return ResourceManager.GetString("Info_PublishInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The publishing process was started..
        /// </summary>
        internal static string Info_PublishInitDetail {
            get {
                return ResourceManager.GetString("Info_PublishInitDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query was aborted.
        /// </summary>
        internal static string SyncStateToolTip_Aborted {
            get {
                return ResourceManager.GetString("SyncStateToolTip_Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item differs from the server version in fields that are not synchronized.
        /// </summary>
        internal static string SyncStateToolTip_Differing {
            get {
                return ResourceManager.GetString("SyncStateToolTip_Differing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item has unpublished changes.
        /// </summary>
        internal static string SyncStateToolTip_Dirty {
            get {
                return ResourceManager.GetString("SyncStateToolTip_Dirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item has been changed in both Word and TFS and the changes cannot be merged automatically.
        /// </summary>
        internal static string SyncStateToolTip_DivergedWithConflicts {
            get {
                return ResourceManager.GetString("SyncStateToolTip_DivergedWithConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item has been changed in both Word and TFS but the changes can be merged automatically.
        /// </summary>
        internal static string SyncStateToolTip_DivergedWithoutConflict {
            get {
                return ResourceManager.GetString("SyncStateToolTip_DivergedWithoutConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item state is unknown.
        /// </summary>
        internal static string SyncStateToolTip_Loading {
            get {
                return ResourceManager.GetString("SyncStateToolTip_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item is new and does not exist on the server.
        /// </summary>
        internal static string SyncStateToolTip_New {
            get {
                return ResourceManager.GetString("SyncStateToolTip_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item does not exist in the document.
        /// </summary>
        internal static string SyncStateToolTip_NotImported {
            get {
                return ResourceManager.GetString("SyncStateToolTip_NotImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item is outdated and needs to be refreshed.
        /// </summary>
        internal static string SyncStateToolTip_Outdated {
            get {
                return ResourceManager.GetString("SyncStateToolTip_Outdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item is up to date and does not need to be synchronized.
        /// </summary>
        internal static string SyncStateToolTip_UpToDate {
            get {
                return ResourceManager.GetString("SyncStateToolTip_UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Path.
        /// </summary>
        internal static string TestCasesSortType_AreaPath {
            get {
                return ResourceManager.GetString("TestCasesSortType_AreaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration Path.
        /// </summary>
        internal static string TestCasesSortType_IterationPath {
            get {
                return ResourceManager.GetString("TestCasesSortType_IterationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sorting.
        /// </summary>
        internal static string TestCasesSortType_None {
            get {
                return ResourceManager.GetString("TestCasesSortType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item Id.
        /// </summary>
        internal static string TestCasesSortType_WorkItemId {
            get {
                return ResourceManager.GetString("TestCasesSortType_WorkItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add location &apos;{0}&apos;, on &apos;{1}&apos;.
        /// </summary>
        internal static string TM_AddError {
            get {
                return ResourceManager.GetString("TM_AddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete template location &apos;{0}&apos;.
        /// </summary>
        internal static string TM_ConfirmDeleteHeader {
            get {
                return ResourceManager.GetString("TM_ConfirmDeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the template location &apos;{0}&apos; (&apos;{1}&apos;)?.
        /// </summary>
        internal static string TM_ConfirmDeleteText {
            get {
                return ResourceManager.GetString("TM_ConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on add.
        /// </summary>
        internal static string TM_MsgErrorOnAdd {
            get {
                return ResourceManager.GetString("TM_MsgErrorOnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on remove.
        /// </summary>
        internal static string TM_MsgErrorOnRemove {
            get {
                return ResourceManager.GetString("TM_MsgErrorOnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on update.
        /// </summary>
        internal static string TM_MsgErrorOnUpdate {
            get {
                return ResourceManager.GetString("TM_MsgErrorOnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not complete remove mapping location &apos;{0}&apos;.
        /// </summary>
        internal static string TM_RemoveError {
            get {
                return ResourceManager.GetString("TM_RemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save updates to location &apos;{0}&apos;, on &apos;{1}&apos;.
        /// </summary>
        internal static string TM_UpdateError {
            get {
                return ResourceManager.GetString("TM_UpdateError", resourceCulture);
            }
        }
    }
}
