//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIT.TFS.SyncService.Adapter.Word2007.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIT.TFS.SyncService.Adapter.Word2007.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hyperlink base of this document is different from the document attachment folder. In order for relative attachment links to work, the hyperlink base needs to point to the document attachment location.
        ///
        ///If you continue, the hyperlink base will be adjusted automatically. Do you want to continue?.
        /// </summary>
        internal static string Attachment_AdjustHyperlinkBaseText {
            get {
                return ResourceManager.GetString("Attachment_AdjustHyperlinkBaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordToTFS Plugin.
        /// </summary>
        internal static string Attachment_AdjustHyperlinkBaseTitle {
            get {
                return ResourceManager.GetString("Attachment_AdjustHyperlinkBaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attachment folder contains attachments that are not linked to from the document. Do you want to delete these files?.
        /// </summary>
        internal static string Attachment_DeleteAttachmentFolderText {
            get {
                return ResourceManager.GetString("Attachment_DeleteAttachmentFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordToTFS Plugin.
        /// </summary>
        internal static string Attachment_DeleteAttachmentFolderTitle {
            get {
                return ResourceManager.GetString("Attachment_DeleteAttachmentFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the hyperlinks within this document points to a file that does not exist. If you move the document or save it to a different location, make sure to move the attachment subfolder as well. If that does not solve the problem, please regenerate the document..
        /// </summary>
        internal static string Attachment_InconsistentFolderStructureText {
            get {
                return ResourceManager.GetString("Attachment_InconsistentFolderStructureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordToTFS Plugin.
        /// </summary>
        internal static string Attachment_InconsistentFolderStructureTitle {
            get {
                return ResourceManager.GetString("Attachment_InconsistentFolderStructureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attachment folder path
        ///&apos;{0}&apos;
        ///is different from the document location
        ///&apos;{1}&apos;.
        ///It is suggested to keep the attachments folder at the same location as the document. Should the folder be moved to
        ///{1}?.
        /// </summary>
        internal static string Attachment_MoveAttachmentFolderText {
            get {
                return ResourceManager.GetString("Attachment_MoveAttachmentFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating work item with template file....
        /// </summary>
        internal static string CreateWorkItemBasedOnTemplate {
            get {
                return ResourceManager.GetString("CreateWorkItemBasedOnTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t close Word document.
        /// </summary>
        internal static string Error_CloseWordDocument {
            get {
                return ResourceManager.GetString("Error_CloseWordDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error converting value.
        /// </summary>
        internal static string Error_Convert {
            get {
                return ResourceManager.GetString("Error_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not saved.
        /// </summary>
        internal static string Error_FileNotSaved {
            get {
                return ResourceManager.GetString("Error_FileNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading document work items.
        /// </summary>
        internal static string Error_LoadWordWI {
            get {
                return ResourceManager.GetString("Error_LoadWordWI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open Word document.
        /// </summary>
        internal static string Error_OpenWordDocument {
            get {
                return ResourceManager.GetString("Error_OpenWordDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item Id &apos;{0}&apos; exists multiple times..
        /// </summary>
        internal static string ExceptionText_DoubleIds {
            get {
                return ResourceManager.GetString("ExceptionText_DoubleIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check and ensure that each work item Id is unique..
        /// </summary>
        internal static string ExceptionText_DoubleIdsExplanation {
            get {
                return ResourceManager.GetString("ExceptionText_DoubleIdsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred on content request in table cell row {0},  column {1}..
        /// </summary>
        internal static string ExceptionText_NoCell {
            get {
                return ResourceManager.GetString("ExceptionText_NoCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table of this work item is different from the related template. Make sure you did not add or delete rows or accidentally merged two tables..
        /// </summary>
        internal static string ExceptionText_SkipInvalidTable {
            get {
                return ResourceManager.GetString("ExceptionText_SkipInvalidTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path of template file is .
        /// </summary>
        internal static string FullPathOfTemplateFile {
            get {
                return ResourceManager.GetString("FullPathOfTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to import.
        /// </summary>
        internal static string Info_NothingToImport {
            get {
                return ResourceManager.GetString("Info_NothingToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document doesn&apos;t contain valid work items to import..
        /// </summary>
        internal static string Info_NothingToImportDetail {
            get {
                return ResourceManager.GetString("Info_NothingToImportDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the insertion of file: {0}. The detailed error message from word is: {1}.
        /// </summary>
        internal static string InteropException_ErrorDuringFileInsert {
            get {
                return ResourceManager.GetString("InteropException_ErrorDuringFileInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WI{0}w: Access to link {1}\n&apos;{2}&apos;\nresults in\n{3}.
        /// </summary>
        internal static string LogService_AccessToLinkMessage {
            get {
                return ResourceManager.GetString("LogService_AccessToLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting work item failed. Cannot find corresponding template file..
        /// </summary>
        internal static string LogService_Export_NoFile {
            get {
                return ResourceManager.GetString("LogService_Export_NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting work item failed. Cannot find table in document..
        /// </summary>
        internal static string LogService_Export_NoTable {
            get {
                return ResourceManager.GetString("LogService_Export_NoTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting work item failed. Work item type does not exist in the current template..
        /// </summary>
        internal static string LogService_Export_NoWorkItem {
            get {
                return ResourceManager.GetString("LogService_Export_NoWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring table because work item type cannot be determined. Check your configuration.
        /// </summary>
        internal static string LogService_TableToWorkItemException {
            get {
                return ResourceManager.GetString("LogService_TableToWorkItemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [] [] [].
        /// </summary>
        internal static string NumberedListItemsTemplate {
            get {
                return ResourceManager.GetString("NumberedListItemsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening the word adapter....
        /// </summary>
        internal static string OpenWordAdapter {
            get {
                return ResourceManager.GetString("OpenWordAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Id.
        /// </summary>
        internal static string ReferenceNameId {
            get {
                return ResourceManager.GetString("ReferenceNameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Rev.
        /// </summary>
        internal static string ReferenceNameRevision {
            get {
                return ResourceManager.GetString("ReferenceNameRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically surrounded text with span tags..
        /// </summary>
        internal static string ResultIfTextIsNotHtml {
            get {
                return ResourceManager.GetString("ResultIfTextIsNotHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selection is null..
        /// </summary>
        internal static string SelectionNotExists {
            get {
                return ResourceManager.GetString("SelectionNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting ScaleWidth and ScaleHeight to 100 failed with message: {0}.
        /// </summary>
        internal static string Shape_Scale100_Failed {
            get {
                return ResourceManager.GetString("Shape_Scale100_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string ShapeOnlyAutoText {
            get {
                return ResourceManager.GetString("ShapeOnlyAutoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark &apos;{0}&apos; not found..
        /// </summary>
        internal static string TestReportError_BookmarkNotFound {
            get {
                return ResourceManager.GetString("TestReportError_BookmarkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to insert test report into a table..
        /// </summary>
        internal static string TestReportError_CursorInTable {
            get {
                return ResourceManager.GetString("TestReportError_CursorInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; not found..
        /// </summary>
        internal static string TestReportError_FileNotFound {
            get {
                return ResourceManager.GetString("TestReportError_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping table because the references table identifier cell (Row={0}, Col={1}) does not exist..
        /// </summary>
        internal static string TheReferencesTableIdentifierCellNotExists {
            get {
                return ResourceManager.GetString("TheReferencesTableIdentifierCellNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the initialization of an additional word instance for file:{0}, the Word specific error was: {1}.
        /// </summary>
        internal static string TitleOfErrorDuringInitOfWordInstance {
            get {
                return ResourceManager.GetString("TitleOfErrorDuringInitOfWordInstance", resourceCulture);
            }
        }
    }
}
