//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFS.SyncService.View.Word2007.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TFS.SyncService.View.Word2007.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap About {
            get {
                object obj = ResourceManager.GetObject("About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitIcon {
            get {
                object obj = ResourceManager.GetObject("aitIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area and Iteration Path.
        /// </summary>
        internal static string AreaIterationPathPanelCaption {
            get {
                return ResourceManager.GetString("AreaIterationPathPanelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BindUnbind {
            get {
                object obj = ResourceManager.GetObject("BindUnbind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap branch {
            get {
                object obj = ResourceManager.GetObject("branch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area und Iteration Path.
        /// </summary>
        internal static string ButtonAreaAndIterationPath {
            get {
                return ResourceManager.GetString("ButtonAreaAndIterationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        internal static string ButtonCompare {
            get {
                return ResourceManager.GetString("ButtonCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Default Values.
        /// </summary>
        internal static string ButtonDefaultValues {
            get {
                return ResourceManager.GetString("ButtonDefaultValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Ids.
        /// </summary>
        internal static string ButtonDeleteIds {
            get {
                return ResourceManager.GetString("ButtonDeleteIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Work Item.
        /// </summary>
        internal static string ButtonEmpyWorkItem {
            get {
                return ResourceManager.GetString("ButtonEmpyWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Work Items.
        /// </summary>
        internal static string ButtonGetWorkItems {
            get {
                return ResourceManager.GetString("ButtonGetWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Header.
        /// </summary>
        internal static string ButtonHeader {
            get {
                return ResourceManager.GetString("ButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Work Item.
        /// </summary>
        internal static string ButtonNewWorkItem {
            get {
                return ResourceManager.GetString("ButtonNewWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string ButtonPublish {
            get {
                return ResourceManager.GetString("ButtonPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string ButtonRefresh {
            get {
                return ResourceManager.GetString("ButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ButtonSettings {
            get {
                return ResourceManager.GetString("ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Result Report.
        /// </summary>
        internal static string ButtonTestResultReport {
            get {
                return ResourceManager.GetString("ButtonTestResultReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Spec Report.
        /// </summary>
        internal static string ButtonTestSpecReport {
            get {
                return ResourceManager.GetString("ButtonTestSpecReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Spec Report By Query.
        /// </summary>
        internal static string ButtonTestSpecReportByQuery {
            get {
                return ResourceManager.GetString("ButtonTestSpecReportByQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Requirement Values.
        /// </summary>
        internal static string DefaultValuesPanelCaption {
            get {
                return ResourceManager.GetString("DefaultValuesPanelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area and Iteration path error.
        /// </summary>
        internal static string Error_AreaAndIterationPath {
            get {
                return ResourceManager.GetString("Error_AreaAndIterationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template &quot;{0}&quot; bound to this document does not exist!.
        /// </summary>
        internal static string Error_BoundTemplateDoesNotExist {
            get {
                return ResourceManager.GetString("Error_BoundTemplateDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template &apos;{0}&apos; used by this document can&apos;t be found. Add the correct template in template manager..
        /// </summary>
        internal static string Error_DocumentTemplateNotExists {
            get {
                return ResourceManager.GetString("Error_DocumentTemplateNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Work Items process error.
        /// </summary>
        internal static string Error_GetWorkItems {
            get {
                return ResourceManager.GetString("Error_GetWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error_MessageBoxTitle {
            get {
                return ResourceManager.GetString("Error_MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected template contains work item mappings that do not map System.Id and System.Rev. Both of these fields are required for Word2Tfs to work correctly..
        /// </summary>
        internal static string Error_MissingFields {
            get {
                return ResourceManager.GetString("Error_MissingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items selected..
        /// </summary>
        internal static string Error_NoWorkItemSelected {
            get {
                return ResourceManager.GetString("Error_NoWorkItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document does not contain any work items to publish.
        /// </summary>
        internal static string Error_NoWorkItemsToPublish {
            get {
                return ResourceManager.GetString("Error_NoWorkItemsToPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document does not contain any work items to refresh..
        /// </summary>
        internal static string Error_NoWorkItemsToRefresh {
            get {
                return ResourceManager.GetString("Error_NoWorkItemsToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish error.
        /// </summary>
        internal static string Error_Publish {
            get {
                return ResourceManager.GetString("Error_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish process error.
        /// </summary>
        internal static string Error_PublishException {
            get {
                return ResourceManager.GetString("Error_PublishException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Report.
        /// </summary>
        internal static string ErrorPanelCaption {
            get {
                return ResourceManager.GetString("ErrorPanelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Issues.
        /// </summary>
        internal static string ErrorPanelText {
            get {
                return ResourceManager.GetString("ErrorPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GetWorkItems {
            get {
                object obj = ResourceManager.GetObject("GetWorkItems", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Work Items.
        /// </summary>
        internal static string GetWorkItemsPanelCaption {
            get {
                return ResourceManager.GetString("GetWorkItemsPanelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IdDelete {
            get {
                object obj = ResourceManager.GetObject("IdDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InsertTemplate {
            get {
                object obj = ResourceManager.GetObject("InsertTemplate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key1 {
            get {
                object obj = ResourceManager.GetObject("key1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial premium period has expired. If you want to use premium edition functionality please register premium edition via &apos;{0}&apos; button in ribbon menu..
        /// </summary>
        internal static string LIC_TrialExpired {
            get {
                return ResourceManager.GetString("LIC_TrialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing ....
        /// </summary>
        internal static string LO_Publish_MainEnd {
            get {
                return ResourceManager.GetString("LO_Publish_MainEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize next step ....
        /// </summary>
        internal static string LO_Publish_MainStart {
            get {
                return ResourceManager.GetString("LO_Publish_MainStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish....
        /// </summary>
        internal static string LO_Publish_Title {
            get {
                return ResourceManager.GetString("LO_Publish_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert table template from &apos;{0}&apos;.
        /// </summary>
        internal static string LogService_InsertTableFromXmlFile {
            get {
                return ResourceManager.GetString("LogService_InsertTableFromXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert template table from &apos;{0}&apos;.
        /// </summary>
        internal static string LogService_InsertTableFromXmlFile_Failed {
            get {
                return ResourceManager.GetString("LogService_InsertTableFromXmlFile_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml file &apos;{0}&apos; does not exist. Cancel Insertion.
        /// </summary>
        internal static string LogService_InsertTableFromXmlFile_FileDoesNotExist {
            get {
                return ResourceManager.GetString("LogService_InsertTableFromXmlFile_FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing add-in.
        /// </summary>
        internal static string LogService_Startup {
            get {
                return ResourceManager.GetString("LogService_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization complete.
        /// </summary>
        internal static string LogService_StartupComplete {
            get {
                return ResourceManager.GetString("LogService_StartupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert table from &apos;{0}&apos; into document.
        /// </summary>
        internal static string nsertTableFromXmlFile_Failed {
            get {
                return ResourceManager.GetString("nsertTableFromXmlFile_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Options {
            get {
                object obj = ResourceManager.GetObject("Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        internal static string PaneTemplateWidth {
            get {
                return ResourceManager.GetString("PaneTemplateWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Preserve {
            get {
                object obj = ResourceManager.GetObject("Preserve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Publish {
            get {
                object obj = ResourceManager.GetObject("Publish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string PublishTitle {
            get {
                return ResourceManager.GetString("PublishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any unpublished local changes will be lost after refresh. Do you want to proceed?.
        /// </summary>
        internal static string Refresh_DoYouReally {
            get {
                return ResourceManager.GetString("Refresh_DoYouReally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document does not contain any identified work items. Make sure you&apos;ve selected the correct Template and team project..
        /// </summary>
        internal static string Refresh_NoIdentifiedWorkItems {
            get {
                return ResourceManager.GetString("Refresh_NoIdentifiedWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more work items could not be found on the server. Make sure you are connected to the correct team project..
        /// </summary>
        internal static string Refresh_SomeNoIdentifiedWorkItems {
            get {
                return ResourceManager.GetString("Refresh_SomeNoIdentifiedWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Selected.
        /// </summary>
        internal static string RefreshSelectedItemButtonLabel {
            get {
                return ResourceManager.GetString("RefreshSelectedItemButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshes all work items within the current selection of the document.
        /// </summary>
        internal static string RefreshSelectedItemButtonScreenTip {
            get {
                return ResourceManager.GetString("RefreshSelectedItemButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing import of Work Items&quot;.
        /// </summary>
        internal static string RefreshWorkItemsAutomaticImpotPreparation {
            get {
                return ResourceManager.GetString("RefreshWorkItemsAutomaticImpotPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establish connection to TFS and gathering information about work items.
        /// </summary>
        internal static string RefreshWorkItemsAutomaticPreparationText {
            get {
                return ResourceManager.GetString("RefreshWorkItemsAutomaticPreparationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Work Items.
        /// </summary>
        internal static string RefreshWorkItemsCaption {
            get {
                return ResourceManager.GetString("RefreshWorkItemsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Refresh Work Items.
        /// </summary>
        internal static string RefreshWorkItemsCaptionAutomatic {
            get {
                return ResourceManager.GetString("RefreshWorkItemsCaptionAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReqDefVals {
            get {
                object obj = ResourceManager.GetObject("ReqDefVals", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReqEmpty {
            get {
                object obj = ResourceManager.GetObject("ReqEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReqVals {
            get {
                object obj = ResourceManager.GetObject("ReqVals", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordToTFS.
        /// </summary>
        internal static string RibbonTab_WordToTFS {
            get {
                return ResourceManager.GetString("RibbonTab_WordToTFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordToTFS (Trial).
        /// </summary>
        internal static string RibbonTab_WordToTFSTrial {
            get {
                return ResourceManager.GetString("RibbonTab_WordToTFSTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap standard {
            get {
                object obj = ResourceManager.GetObject("standard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StyleCustomize {
            get {
                object obj = ResourceManager.GetObject("StyleCustomize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StyleDelete {
            get {
                object obj = ResourceManager.GetObject("StyleDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item Overview.
        /// </summary>
        internal static string SynchronizationStatePanelCaption {
            get {
                return ResourceManager.GetString("SynchronizationStatePanelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table_refresh {
            get {
                object obj = ResourceManager.GetObject("table_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Manager.
        /// </summary>
        internal static string TemplateManagerPanelCaption {
            get {
                return ResourceManager.GetString("TemplateManagerPanelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestResultReport {
            get {
                object obj = ResourceManager.GetObject("TestResultReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Result Report.
        /// </summary>
        internal static string TestResultReportPanelCaption {
            get {
                return ResourceManager.GetString("TestResultReportPanelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestSpecificationReport {
            get {
                object obj = ResourceManager.GetObject("TestSpecificationReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Specification Report by Query.
        /// </summary>
        internal static string TestSpecificationReportByQueryPanelCaption {
            get {
                return ResourceManager.GetString("TestSpecificationReportByQueryPanelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Specification Report.
        /// </summary>
        internal static string TestSpecificationReportPanelCaption {
            get {
                return ResourceManager.GetString("TestSpecificationReportPanelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string TFSBindTeamProjectDisconnectLabel {
            get {
                return ResourceManager.GetString("TFSBindTeamProjectDisconnectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string TFSBindTeamProjectLabel {
            get {
                return ResourceManager.GetString("TFSBindTeamProjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind To Team Project.
        /// </summary>
        internal static string TFSBindTeamProjectScreenTip {
            get {
                return ResourceManager.GetString("TFSBindTeamProjectScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind the current document to a specific team project on the Team Foundation Server.
        /// </summary>
        internal static string TFSBindTeamProjectSuperTip {
            get {
                return ResourceManager.GetString("TFSBindTeamProjectSuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;disconnected&gt;.
        /// </summary>
        internal static string TFSProjectDisconnected {
            get {
                return ResourceManager.GetString("TFSProjectDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any unpublished local changes will be lost after refresh. Do you want to proceed?.
        /// </summary>
        internal static string TFSRefresh_LocalChanges {
            get {
                return ResourceManager.GetString("TFSRefresh_LocalChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any unpublished local changes to {0} will be lost after refresh. Do you want to proceed?.
        /// </summary>
        internal static string TFSRefreshSelected_LocalChanges {
            get {
                return ResourceManager.GetString("TFSRefreshSelected_LocalChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;disconnected&gt;.
        /// </summary>
        internal static string TFSServerDisconnected {
            get {
                return ResourceManager.GetString("TFSServerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string TFSUnbindTeamProjectLabel {
            get {
                return ResourceManager.GetString("TFSUnbindTeamProjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbind Team Project.
        /// </summary>
        internal static string TFSUnbindTeamProjectScreenTip {
            get {
                return ResourceManager.GetString("TFSUnbindTeamProjectScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbind the current document from a specific team project on the Team Foundation Server.
        /// </summary>
        internal static string TFSUnbindTeamProjectSuperTip {
            get {
                return ResourceManager.GetString("TFSUnbindTeamProjectSuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select template &apos;{0}&apos; from &apos;{1}&apos;..
        /// </summary>
        internal static string TM_ToolTip {
            get {
                return ResourceManager.GetString("TM_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to insert a table on this position - nested tables not allowed..
        /// </summary>
        internal static string WordToTFS_Error_TableInsertInTable {
            get {
                return ResourceManager.GetString("WordToTFS_Error_TableInsertInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordToTFS.
        /// </summary>
        internal static string WordToTFS_Error_Title {
            get {
                return ResourceManager.GetString("WordToTFS_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        internal static string WordToTFS_Error_UnexpectedErrorTitle {
            get {
                return ResourceManager.GetString("WordToTFS_Error_UnexpectedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.aitgmbh.de/feedback_wordtotfs.0.html.
        /// </summary>
        internal static string WordToTFS_FeedbackWebPage {
            get {
                return ResourceManager.GetString("WordToTFS_FeedbackWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://URL_Help.
        /// </summary>
        internal static string WordToTFS_Help {
            get {
                return ResourceManager.GetString("WordToTFS_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all work item ids?.
        /// </summary>
        internal static string WordToTFS_IdDeletionCation {
            get {
                return ResourceManager.GetString("WordToTFS_IdDeletionCation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete all work item ids from published requirements in this document. After saving the document, this operation is not recoverable and prevents you from synchronizing further changes to TFS.
        ///
        ///Do you want to delete all work item ids?.
        /// </summary>
        internal static string WordToTFS_IdDeletionDialog {
            get {
                return ResourceManager.GetString("WordToTFS_IdDeletionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://URL_Update.
        /// </summary>
        internal static string WordToTFS_Update {
            get {
                return ResourceManager.GetString("WordToTFS_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty .
        /// </summary>
        internal static string WorkItemPrefix_Empty {
            get {
                return ResourceManager.GetString("WorkItemPrefix_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New .
        /// </summary>
        internal static string WorkItemPrefix_New {
            get {
                return ResourceManager.GetString("WorkItemPrefix_New", resourceCulture);
            }
        }
    }
}
